### ISSUE TITLE
New check: legal statement IDs for policies

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cfn-python-lint#1376] opened 2020-02-20 16:22 UTC
*cfn-lint version: (`cfn-lint --version`)* 0.26.2
Using latest specs

*Description of issue.*

cfn-lint does not check that statement IDs used in IAM policies are named correctly. Stack failures like the following can occur:

`Statement IDs (SID) must be alpha-numeric. Check that your input satisfies the regular expression [0-9A-Za-z]* (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: )`

**Comment by PatMyron** [comment] 2020-02-20 17:54
closing as duplicate of https://github.com/aws-cloudformation/cfn-python-lint/issues/708

**Closed by PatMyron** 2020-02-20 17:54 UTC
