### ISSUE TITLE
AWS::ECS::TaskDefinition strict attributes

### ISSUE THREAD

**Issue by deleugpn** [aws-cloudformation/cfn-python-lint#1514] opened 2020-05-06 17:53 UTC
*cfn-lint version: 0.30.1*

*Description of issue.*
Attributes **Cpu** and **Memory** are too strict for `AWS::ECS::TaskDefinition`. They are [documented as String](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu) but they are obviously numbers. As such, it would be nice if we could use numeric values in our templates for better readability.

Template sample:

```
  ProxyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: task
          Name: nginx
          PortMappings:
            - ContainerPort: 80
          Privileged: false
      Cpu: 512
      Memory: 1024
      Family: nginx-proxy
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRoleArn
      TaskRoleArn: !ImportValue ECSTaskExecutionRoleArn
      RequiresCompatibilities: [FARGATE]
```

**Comment by PatMyron** [comment] 2020-05-06 19:59
duplicate of https://github.com/aws-cloudformation/cfn-python-lint/issues/547

**Closed by PatMyron** 2020-05-06 19:59 UTC
